import { useEffect, useMemo, useState } from 'react'
import './App.css'

const API_URL = import.meta.env.VITE_API_URL || 'https://karthiable.onrender.com'

const starterPreview = `<!DOCTYPE html>
<html>
  <head>
    <style>
      * { box-sizing: border-box; }
      body {
        margin: 0;
        min-height: 100vh;
        color: white;
        font-family: Inter, ui-sans-serif, system-ui, sans-serif;
        background:
          radial-gradient(circle at 74% 46%, rgba(155, 46, 255, .34), transparent 24%),
          radial-gradient(circle at 44% 88%, rgba(0, 98, 255, .4), transparent 26%),
          #030613;
        overflow: hidden;
      }
      .window { padding: 16px 20px; height: 100vh; border: 1px solid rgba(126, 87, 255, .35); }
      .top { display: flex; align-items: center; gap: 8px; margin-bottom: 46px; }
      .dot { width: 8px; height: 8px; border-radius: 999px; background: #576178; }
      .bar { width: 260px; height: 16px; border: 1px solid rgba(138, 119, 255, .35); border-radius: 999px; margin-left: 10px; }
      .hero { display: grid; grid-template-columns: 1fr 180px; align-items: center; gap: 30px; }
      h1 { margin: 0; font-size: 28px; line-height: 1.08; }
      h1 span { color: #ff3df2; }
      .line { width: 82%; height: 4px; margin-top: 18px; border-radius: 999px; background: linear-gradient(90deg, #4963ff, #8d2bff, transparent); }
      .line.small { width: 58%; margin-top: 8px; opacity: .72; }
      .button { width: 126px; height: 34px; margin-top: 22px; border-radius: 9px; border: 1px solid #0166ff; box-shadow: 0 0 18px #0166ff; }
      .cube {
        width: 140px; height: 140px; border: 2px solid #8a2dff; transform: rotate(30deg) skew(-8deg);
        box-shadow: 0 0 35px #9b2eff, inset 0 0 30px rgba(155, 46, 255, .45);
      }
      .grid {
        position: absolute; inset: auto -40px 0; height: 130px;
        background: linear-gradient(rgba(82, 42, 255, .45) 1px, transparent 1px),
          linear-gradient(90deg, rgba(82, 42, 255, .45) 1px, transparent 1px);
        background-size: 34px 28px;
        transform: perspective(360px) rotateX(64deg);
        transform-origin: bottom;
      }
    </style>
  </head>
  <body>
    <div class="window">
      <div class="top"><i class="dot"></i><i class="dot"></i><i class="dot"></i><div class="bar"></div></div>
      <div class="hero">
        <div>
          <h1>Future of the web,<br />generated by <span>AI</span></h1>
          <div class="line"></div>
          <div class="line small"></div>
          <div class="button"></div>
        </div>
        <div class="cube"></div>
      </div>
      <div class="grid"></div>
    </div>
  </body>
</html>`

const featureCards = [
  { title: 'AI Powered', text: 'Generate high-quality web apps using the power of AI.', icon: 'bolt' },
  { title: 'Clean Code', text: 'Get responsive, production-ready HTML every time.', icon: 'code' },
  { title: 'Beautiful UI', text: 'Create futuristic designs that feel polished fast.', icon: 'spark' },
  { title: 'Deploy Fast', text: 'Preview, download, and ship your generated page.', icon: 'rocket' },
]

const sidebarItems = ['Dashboard', 'Generate', 'My Projects', 'Templates', 'Chat History', 'Favorites', 'Settings']

const examples = [
  'A futuristic dashboard for analytics with neon charts',
  'A modern SaaS landing page for an AI coding assistant',
  'An e-commerce store homepage for premium sneakers',
]

function timeAgo(timestamp, now) {
  const seconds = Math.max(1, Math.floor((now - timestamp) / 1000))
  if (seconds < 60) return 'just now'
  const minutes = Math.floor(seconds / 60)
  if (minutes < 60) return `${minutes} min${minutes > 1 ? 's' : ''} ago`
  const hours = Math.floor(minutes / 60)
  if (hours < 24) return `${hours} hour${hours > 1 ? 's' : ''} ago`
  const days = Math.floor(hours / 24)
  return `${days} day${days > 1 ? 's' : ''} ago`
}

function Icon({ name }) {
  const icons = {
    bolt: 'M12 2 4 14h7l-1 8 8-13h-7l1-7Z',
    code: 'M8 8 3 12l5 4M16 8l5 4-5 4M14 4l-4 16',
    spark: 'M12 2l2.2 6.3L20 11l-5.8 2.7L12 20l-2.2-6.3L4 11l5.8-2.7L12 2Z',
    rocket: 'M14 4c3.2 0 5-2 6-3-.3 3.3-1.4 6-3.4 8L18 14l-4.8-1.4L10 16l-2-2 3.4-3.2L10 6l5 1.4C15.5 6.5 15.8 5.5 16 4h-2Z',
    grid: 'M4 4h6v6H4V4Zm10 0h6v6h-6V4ZM4 14h6v6H4v-6Zm10 0h6v6h-6v-6Z',
    search: 'M10.5 4a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13Zm5 11 4.5 4.5',
    plus: 'M12 5v14M5 12h14',
    external: 'M14 4h6v6M20 4l-9 9M20 14v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h5',
  }

  return (
    <svg viewBox="0 0 24 24" aria-hidden="true">
      <path d={icons[name]} />
    </svg>
  )
}

function App() {
  const [prompt, setPrompt] = useState('')
  const [previewHtml, setPreviewHtml] = useState(starterPreview)
  const [status, setStatus] = useState('Ready')
  const [isGenerating, setIsGenerating] = useState(false)
  const [error, setError] = useState('')
  const [now] = useState(() => Date.now())
  const [recent, setRecent] = useState(() => {
    try {
      return JSON.parse(localStorage.getItem('karthiable-recent')) || []
    } catch {
      return []
    }
  })

  useEffect(() => {
    localStorage.setItem('karthiable-recent', JSON.stringify(recent.slice(0, 6)))
  }, [recent])

  const canDownload = useMemo(() => previewHtml.trim().startsWith('<!DOCTYPE html>'), [previewHtml])
  const displayedRecent = recent.length ? recent : [
    { id: 'sample-1', title: 'Modern SaaS Landing Page', prompt: examples[1], html: starterPreview, createdAt: now - 120000 },
    { id: 'sample-2', title: 'AI Dashboard UI', prompt: examples[0], html: starterPreview, createdAt: now - 900000 },
    { id: 'sample-3', title: 'E-commerce Store', prompt: examples[2], html: starterPreview, createdAt: now - 3600000 },
  ]

  async function handleGenerate(event) {
    event.preventDefault()
    const trimmedPrompt = prompt.trim()
    if (!trimmedPrompt) {
      setError('Describe what you want to build first.')
      return
    }

    setIsGenerating(true)
    setStatus('Generating')
    setError('')

    try {
      const response = await fetch(`${API_URL}/generate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: trimmedPrompt }),
      })

      if (!response.ok) {
        throw new Error(`Backend returned ${response.status}`)
      }

      const html = await response.text()
      setPreviewHtml(html)
      setStatus('Ready')
      setRecent((items) => [
        {
          id: crypto.randomUUID(),
          title: trimmedPrompt.length > 34 ? `${trimmedPrompt.slice(0, 34)}...` : trimmedPrompt,
          prompt: trimmedPrompt,
          html,
          createdAt: Date.now(),
        },
        ...items,
      ].slice(0, 6))
    } catch (err) {
      setStatus('Offline')
      setError(`Could not reach the generator at ${API_URL}. Start the backend and try again.`)
      console.error(err)
    } finally {
      setIsGenerating(false)
    }
  }

  function handleDownload() {
    const blob = new Blob([previewHtml], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = 'karthiable-generated.html'
    link.click()
    URL.revokeObjectURL(url)
  }

  function loadRecent(item) {
    setPrompt(item.prompt)
    setPreviewHtml(item.html)
    setStatus('Ready')
    setError('')
  }

  return (
    <div className="app-shell">
      <aside className="sidebar">
        <div className="brand">
          <div className="brand-mark">K</div>
          <span>KARTHIABLE</span>
        </div>

        <nav className="nav-list" aria-label="Main navigation">
          {sidebarItems.map((item, index) => (
            <button className={index === 0 ? 'active' : ''} type="button" key={item}>
              <span className="nav-icon"><Icon name={index === 0 ? 'grid' : 'spark'} /></span>
              {item}
            </button>
          ))}
        </nav>

        <div className="upgrade-card">
          <strong>Upgrade to Pro</strong>
          <p>Unlimited Generations</p>
          <p>Priority Access</p>
          <p>Export and Deploy</p>
          <button type="button">Upgrade Now</button>
        </div>

        <div className="profile-card">
          <div className="avatar">K</div>
          <div>
            <strong>Karthi</strong>
            <span>Pro Plan</span>
          </div>
        </div>
      </aside>

      <main className="main-panel">
        <header className="topbar">
          <label className="search-box">
            <Icon name="search" />
            <input type="search" placeholder="Search anything..." />
            <kbd>Ctrl K</kbd>
          </label>

          <div className="top-actions">
            <button type="button" className="icon-button" aria-label="Theme toggle">o</button>
            <button type="button" className="icon-button" aria-label="Notifications">!</button>
            <button
              className="new-project"
              type="button"
              onClick={() => {
                setPrompt('')
                setPreviewHtml(starterPreview)
                setStatus('Ready')
                setError('')
              }}
            >
              New Project <Icon name="plus" />
            </button>
          </div>
        </header>

        <section className="hero-section">
          <div className="orbital-glow" />
          <p className="eyebrow">Describe it. Generate it. Launch it.</p>
          <h1>KARTHIABLE</h1>
          <p className="hero-copy">
            The AI-powered web app generator that turns your ideas into beautiful,
            functional websites in seconds.
          </p>
        </section>

        <form className="prompt-card" onSubmit={handleGenerate}>
          <label htmlFor="prompt">What do you want to build?</label>
          <textarea
            id="prompt"
            value={prompt}
            onChange={(event) => setPrompt(event.target.value)}
            placeholder="E.g. A futuristic dashboard for analytics..."
          />

          <div className="prompt-actions">
            <div className="chips">
              {examples.map((example) => (
                <button key={example} type="button" onClick={() => setPrompt(example)}>
                  {example.includes('landing') ? 'Landing Page' : example.includes('store') ? 'Storefront' : 'Web App'}
                </button>
              ))}
            </div>
            <div className="generate-actions">
              <button type="button" className="ghost-button" onClick={() => setPrompt((value) => `${value} Make it premium, responsive, and animated.`.trim())}>
                Enhance
              </button>
              <button className="primary-button" type="submit" disabled={isGenerating}>
                {isGenerating ? 'Generating...' : 'Generate'}
              </button>
            </div>
          </div>
          {error && <p className="error-message">{error}</p>}
        </form>

        <section className="inline-preview-card" aria-label="Generated website preview">
          <div className="preview-heading">
            <div>
              <span className={`status ${status.toLowerCase()}`}>{status}</span>
              <h2>Generated Page Preview</h2>
            </div>
            <button type="button" onClick={handleDownload} disabled={!canDownload}>
              Download HTML
            </button>
          </div>
          <div className="large-browser-frame">
            {isGenerating && (
              <div className="preview-loader">
                <span />
                Building your website preview...
              </div>
            )}
            <iframe title="Generated website full preview" srcDoc={previewHtml} sandbox="allow-scripts" />
          </div>
        </section>

        <section className="feature-grid">
          {featureCards.map((feature) => (
            <article className="feature-card" key={feature.title}>
              <div className="feature-icon"><Icon name={feature.icon} /></div>
              <h2>{feature.title}</h2>
              <p>{feature.text}</p>
            </article>
          ))}
        </section>

        <section className="cta-card">
          <div className="mini-cube" />
          <div>
            <h2>Your ideas. Our AI. Limitless possibilities.</h2>
            <p>Start building the future with Karthiable.</p>
          </div>
          <button type="button" onClick={handleGenerate} disabled={isGenerating || !prompt.trim()}>
            Get Started Now
          </button>
        </section>
      </main>

      <aside className="preview-panel">
        <section className="preview-card">
          <div className="section-title">
            <h2>Mini Preview</h2>
            <span className={`status ${status.toLowerCase()}`}>{status}</span>
            <button type="button" onClick={handleDownload} disabled={!canDownload} aria-label="Download generated HTML">
              <Icon name="external" />
            </button>
          </div>
          <div className="browser-frame">
            <iframe title="Generated website preview" srcDoc={previewHtml} sandbox="allow-scripts" />
          </div>
        </section>

        <section className="recent-card">
          <div className="section-title">
            <h2>Recent Generations</h2>
            <button type="button" onClick={() => setRecent([])}>Clear</button>
          </div>

          <div className="recent-list">
            {displayedRecent.map((item) => (
              <button className="recent-item" type="button" key={item.id} onClick={() => loadRecent(item)}>
                <span className="thumb" />
                <span>
                  <strong>{item.title}</strong>
                  <small>{timeAgo(item.createdAt, now)}</small>
                </span>
                <i>...</i>
              </button>
            ))}
          </div>
        </section>
      </aside>
    </div>
  )
}

export default App
